// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SupportAPI.Helpers;

#nullable disable

namespace SupportAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231009082615_MakeNullable")]
    partial class MakeNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SupportAPI.Common.Entities.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentId")
                        .HasColumnType("text");

                    b.Property<DateTime>("ClosedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("SupportAPI.Common.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSentByAgent")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("SupportAPI.Common.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FinishAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsNightShift")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOverflow")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e491ffff-b197-4cdf-859c-a103bdf63fc5"),
                            FinishAt = new DateTime(2023, 12, 31, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            IsNightShift = false,
                            IsOnline = false,
                            IsOverflow = false,
                            MaxCapacity = 0,
                            StartAt = new DateTime(2023, 12, 31, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamName = "Team A"
                        },
                        new
                        {
                            Id = new Guid("675d7017-f2f6-4460-9405-36bcf16fbc1e"),
                            FinishAt = new DateTime(2023, 12, 31, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            IsNightShift = false,
                            IsOnline = false,
                            IsOverflow = false,
                            MaxCapacity = 0,
                            StartAt = new DateTime(2023, 12, 31, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamName = "Team B"
                        },
                        new
                        {
                            Id = new Guid("e6f027fb-2f6d-4f45-8d95-a53f1e813bec"),
                            FinishAt = new DateTime(2023, 12, 31, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            IsNightShift = true,
                            IsOnline = false,
                            IsOverflow = false,
                            MaxCapacity = 0,
                            StartAt = new DateTime(2023, 12, 31, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamName = "Team C"
                        },
                        new
                        {
                            Id = new Guid("1199495b-9684-4ab3-84f3-d6ff04ac8d83"),
                            FinishAt = new DateTime(2023, 12, 31, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            IsNightShift = false,
                            IsOnline = false,
                            IsOverflow = true,
                            MaxCapacity = 0,
                            StartAt = new DateTime(2023, 12, 31, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamName = "Overflow Team"
                        });
                });

            modelBuilder.Entity("SupportAPI.Common.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SupportAPI.Common.Entities.Agent", b =>
                {
                    b.HasBaseType("SupportAPI.Common.Entities.User");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<int>("Seniority")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasIndex("TeamId");

                    b.HasDiscriminator().HasValue("Agent");

                    b.HasData(
                        new
                        {
                            Id = "d3af35de-eebc-4966-a443-5a70dd21d44f",
                            IsOnline = false,
                            Seniority = 3,
                            TeamId = new Guid("e491ffff-b197-4cdf-859c-a103bdf63fc5")
                        },
                        new
                        {
                            Id = "c546976c-ac25-4f8e-bb1c-d450e4be149f",
                            IsOnline = false,
                            Seniority = 1,
                            TeamId = new Guid("e491ffff-b197-4cdf-859c-a103bdf63fc5")
                        },
                        new
                        {
                            Id = "d875a149-daee-48c7-adef-82d792963994",
                            IsOnline = false,
                            Seniority = 1,
                            TeamId = new Guid("e491ffff-b197-4cdf-859c-a103bdf63fc5")
                        },
                        new
                        {
                            Id = "24bb36a8-d98f-4d90-83c5-a86a7c1287bd",
                            IsOnline = false,
                            Seniority = 0,
                            TeamId = new Guid("e491ffff-b197-4cdf-859c-a103bdf63fc5")
                        },
                        new
                        {
                            Id = "95d5ba96-d9d8-4159-af92-965d2e42c56c",
                            IsOnline = false,
                            Seniority = 2,
                            TeamId = new Guid("675d7017-f2f6-4460-9405-36bcf16fbc1e")
                        },
                        new
                        {
                            Id = "d4077d2b-281e-4ac8-a631-7c33acb5a8c9",
                            IsOnline = false,
                            Seniority = 1,
                            TeamId = new Guid("675d7017-f2f6-4460-9405-36bcf16fbc1e")
                        },
                        new
                        {
                            Id = "37231e48-80d6-4003-b809-2cfff75f1573",
                            IsOnline = false,
                            Seniority = 1,
                            TeamId = new Guid("675d7017-f2f6-4460-9405-36bcf16fbc1e")
                        },
                        new
                        {
                            Id = "fa73bd41-1589-4da9-a060-6a86745f2dd4",
                            IsOnline = false,
                            Seniority = 0,
                            TeamId = new Guid("675d7017-f2f6-4460-9405-36bcf16fbc1e")
                        },
                        new
                        {
                            Id = "123b3625-e965-4bdd-99c5-b5d8c346cd75",
                            IsOnline = false,
                            Seniority = 1,
                            TeamId = new Guid("e6f027fb-2f6d-4f45-8d95-a53f1e813bec")
                        },
                        new
                        {
                            Id = "f6df3a11-a0be-4656-81f8-25d8d0700fed",
                            IsOnline = false,
                            Seniority = 1,
                            TeamId = new Guid("e6f027fb-2f6d-4f45-8d95-a53f1e813bec")
                        },
                        new
                        {
                            Id = "ae474024-aa1d-4aa3-83d1-9154a2a7028e",
                            IsOnline = false,
                            Seniority = 0,
                            TeamId = new Guid("e6f027fb-2f6d-4f45-8d95-a53f1e813bec")
                        },
                        new
                        {
                            Id = "95c25b46-dd5f-459a-9abd-aa53a546fd12",
                            IsOnline = false,
                            Seniority = 0,
                            TeamId = new Guid("e6f027fb-2f6d-4f45-8d95-a53f1e813bec")
                        },
                        new
                        {
                            Id = "d20f7ae0-cdea-4d35-ae99-6ebe20a69733",
                            IsOnline = false,
                            Seniority = 0,
                            TeamId = new Guid("e6f027fb-2f6d-4f45-8d95-a53f1e813bec")
                        },
                        new
                        {
                            Id = "42c7a71a-23fa-4620-94a1-538d01eee12b",
                            IsOnline = false,
                            Seniority = 0,
                            TeamId = new Guid("e6f027fb-2f6d-4f45-8d95-a53f1e813bec")
                        },
                        new
                        {
                            Id = "ecc90153-6e62-490c-b130-934ac75d1ced",
                            IsOnline = false,
                            Seniority = 0,
                            TeamId = new Guid("e6f027fb-2f6d-4f45-8d95-a53f1e813bec")
                        },
                        new
                        {
                            Id = "cd91b628-8a22-4581-91f4-1f67f87b83e6",
                            IsOnline = false,
                            Seniority = 0,
                            TeamId = new Guid("e6f027fb-2f6d-4f45-8d95-a53f1e813bec")
                        });
                });

            modelBuilder.Entity("SupportAPI.Common.Entities.Customer", b =>
                {
                    b.HasBaseType("SupportAPI.Common.Entities.User");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.HasDiscriminator().HasValue("Customer");

                    b.HasData(
                        new
                        {
                            Id = "3d2f8c6a-a206-4f99-a2ff-c5206c41741b",
                            AccountId = new Guid("7100d2c8-918f-4d12-809b-28995482d85d")
                        });
                });

            modelBuilder.Entity("SupportAPI.Common.Entities.Chat", b =>
                {
                    b.HasOne("SupportAPI.Common.Entities.Agent", "Agent")
                        .WithMany("Chats")
                        .HasForeignKey("AgentId");

                    b.HasOne("SupportAPI.Common.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SupportAPI.Common.Entities.Message", b =>
                {
                    b.HasOne("SupportAPI.Common.Entities.Chat", null)
                        .WithMany("Messages")
                        .HasForeignKey("ChatId");

                    b.HasOne("SupportAPI.Common.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SupportAPI.Common.Entities.Agent", b =>
                {
                    b.HasOne("SupportAPI.Common.Entities.Team", "Team")
                        .WithMany("Agents")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SupportAPI.Common.Entities.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("SupportAPI.Common.Entities.Team", b =>
                {
                    b.Navigation("Agents");
                });

            modelBuilder.Entity("SupportAPI.Common.Entities.Agent", b =>
                {
                    b.Navigation("Chats");
                });
#pragma warning restore 612, 618
        }
    }
}
